name: main

# Controls when the workflow will run
on:
  push:
  workflow_dispatch:
  pull_request:
    # inputs:
    #   datacenter:
    #     description: Select the Github Runner Datacenter
    #     default: 'KC'
    #     type: choice
    #     options: 
    #     - KC
    #     - LA

jobs:
#   Validate:
#     runs-on: [self-hosted,Development,Linux]
    
#     steps:
#       - uses: actions/checkout@v3

#       - name: Terraform Init
#         uses: docker://hashicorp/terraform:1.5
#         with:
#           args:
#             -chdir=./terraform init -backend=false
      
#       - name: Terraform Validate
#         uses: docker://hashicorp/terraform:1.5
#         with:
#           args: 
#             -chdir=./terraform validate          


#       - name: Static Code Analysis
#         uses: docker://bridgecrew/checkov:2.0.485
#         with:
#           entrypoint: /usr/local/bin/checkov
#           args:
#             -d terraform

  Plan:
    runs-on: ubuntu-latest
    permissions: 
        pull-requests: write 


    steps:
      - uses: actions/checkout@v3 

      - name: Terraform Init
        uses: docker://hashicorp/terraform:1.5
        with:
          args: 
            -chdir=./terraform init


      - name: Terraform Plan
        id: plan
        uses: docker://hashicorp/terraform:1.5
        with:
          entrypoint: /bin/sh
          args: 
            -c "terraform -chdir=./terraform plan -no-color >> plan.txt"

      - name: RUN
        run: | 
          ls -lha
          ls -lha terraform

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: plan.txt
          comment_tag: plan
          mode: upsert            